version: "3.9"
services:
  dyslexia-app-backend:
    build: .
    ports:
      - "62345:62345"
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "62344:27017"
volumes:
  mongo-data:
